feat(payment): update payment success page to new designs
mozilla/fxa pull request #10138
Opened 2021-08-17 19:28 UTC by vbudhram

## Because

- We need to update these to match new figma designs

## This pull request

- Updates designs from https://www.figma.com/file/cOIAuHIIbrPbAlAIcpejNM/%F0%9F%8E%A1MVP-Subscription-Optimization-Flow?node-id=400%3A2098

## Issue that this pull request solves

Closes: https://github.com/mozilla/fxa/issues/9365

## Checklist

- [x] My commit is GPG signed.
- [ ] If applicable, I have modified or added tests which pass locally.
- [ ] I have added necessary documentation (if appropriate).
- [ ] I have verified that my changes render correctly in RTL (if appropriate).

## Screenshots (Optional)

Please attach the screenshots of the changes made in case of change in user interface.

## Other information (Optional)

Any other information that is important to this pull request.

2021-08-17 23:57 UTC, biancadanforth commented
@vbudhram Hello! Would you mind [adding a comment in `main.ftl` explaining what `productName` is](https://github.com/mozilla/fxa/pull/10127#discussion_r690530258) for the message string with id `"fxa-account-signup-error"`? I neglected to do that in my PR that was merged earlier.

2021-08-18 12:54 UTC, meandavejustice commented
The `yarn build` command is failling in ci:

```
TypeScript error in /home/circleci/project/packages/fxa-payments-server/src/routes/Product/index.tsx(208,10):
Property 'accountExists' is missing in type '{ plan: Plan; customer: Customer; profile: Profile; isMobile: boolean; }' but required in type 'SubscriptionSuccessProps'.  TS2741

    206 |     if (alreadySubscribedToSelectedPlan) {
    207 |       return (
  > 208 |         <SubscriptionSuccess
        |          ^
    209 |           {...{
    210 |             plan: selectedPlan,
    211 |             customer: customer.result,
```

2021-08-18 15:10 UTC, meandavejustice requested changes
This looks pretty good, I noticed a couple little style tweaks to get this to match the figma more precisely.

1. It looks like font-weight needs to be set on the `.subtitle` element.
2. spacing between `.subtitle` and the header containing `.checkmark` icon should be closer to 32px
3. spacing between legal links at the bottom does not match the initial state of the checkout page.

![image](https://user-images.githubusercontent.com/1844554/129922970-25e96dd5-a56f-4f50-9120-fca044086857.png)

![image](https://user-images.githubusercontent.com/1844554/129923489-794a3ad0-ef61-4e6f-b420-40b8c38da173.png)

2021-08-18 15:13 UTC, biancadanforth reviewed
Hey Vijay -- I know this is still a WIP. I was just passing through and thought I'd see how things were going. :-)

2021-08-18 15:13 UTC, biancadanforth commented on packages/fxa-payments-server/src/components/PaymentConfirmation/index.tsx
>            </Localized>
We probably need to differentially show these messages based on `accountExists` too. Right now I see the passwordless strings when I sign up with an existing FxA account locally.

2021-08-18 16:24 UTC, meandavejustice approved these changes
LGTM, thanks for picking up this task last minute @vbudhram, we appreciate it :)

2021-08-18 16:38 UTC, merged