Train 220.4
mozilla/fxa pull request #11251
Opened 2021-12-06 18:32 UTC by jodyheavener

Fixes admin-server

2021-12-06 19:58 UTC, vbudhram approved these changes

2021-12-06 20:23 UTC, jodyheavener commented
@vbudhram this doesn't appear to have run the build and deploy job - any idea why?

2021-12-06 21:58 UTC, vbudhram requested changes
I take back my r+ 😂, looks like train 220 has commits from main. We should reset this branch to 220.4 before resolving conflicts.

@jodyheavener Did you intend to make a merge branch instead of train branch?

2021-12-07 16:12 UTC, vbudhram approved these changes

2021-12-07 20:05 UTC, closed without merging