chore(tests): Fix uncalled .toBeInTheDocument and .toBeTruthy referen…
mozilla/fxa pull request #12892
Opened 2022-05-16 17:57 UTC by pdehaan

…ces in tests

## Because

- `.toBeInDocument` should be `.toBeInDocument()`, etc.

## This pull request

- Fixes the errors, but doesn't add ESLint rules to catch future breakages, I'll file that as a separate issue.

## Issue that this pull request solves

Closes: #12868

## Checklist

_Put an `x` in the boxes that apply_

- [x] My commit is GPG signed.
- [ ] If applicable, I have modified or added tests which pass locally.
- [ ] I have added necessary documentation (if appropriate).
- [ ] I have verified that my changes render correctly in RTL (if appropriate).

## Screenshots (Optional)

Please attach the screenshots of the changes made in case of change in user interface.

## Other information (Optional)

Any other information that is important to this pull request.

2022-05-16 18:47 UTC, dschom approved these changes
LGTM!

2022-05-16 19:45 UTC, LZoog requested changes
I know I mentioned this on Slack but just also calling out here that `test_pull_request` didn't run. I'm pretty certain [this one](https://github.com/mozilla/fxa/pull/12892/files#diff-6fc91d2a0800ce1b0e1e74450b7a897939990bf021fea75e42ef703098f0234fR26) doesn't pass locally since I tried fixing that one before.

We had some issues with CI running last week, I can't tell if that's what's happened here or if it didn't run since you're not in fxa-devs? 🤔 But either way, if you run `yarn test` in `fxa-settings` you should see at least that one fail (unless I'm somehow mistaken on that not passing). If that's something you can investigate I can come back and re-review/pull your commit into a different branch, or otherwise, we can have a separate ticket for just that one failure and I can r+ the rest.

2022-05-17 21:42 UTC, LZoog commented on packages/fxa-settings/src/components/BentoMenu/index.test.tsx
> +    expect(dropDown).toBeInTheDocument();
Yeah, those should not be `null`. That's what I was running into as well.

If you revert the `BentoMenu` and `DropDownAvatarMenu` changes, I can pull your commit into another PR for you (we actually have docs on how to do this [here](https://mozilla.github.io/ecosystem-platform/reference/team-processes/development-process#merging-a-contributors-pr) FWIW), and then we can have a separate issue to fix those remaining ones.

2022-05-17 22:40 UTC, pdehaan commented on packages/fxa-settings/src/components/BentoMenu/index.test.tsx
> +    expect(dropDown).toBeInTheDocument();
/giphy "As you wish"

```
git grep -n ".toBe" packages | grep -Ev "\.toBe.*\("

packages/fxa-settings/src/components/BentoMenu/index.test.tsx:26:    expect(dropDown).toBeInTheDocument;
packages/fxa-settings/src/components/BentoMenu/index.test.tsx:38:    expect(dropDown).toBeInTheDocument;
packages/fxa-settings/src/components/BentoMenu/index.test.tsx:54:    expect(dropDown).toBeInTheDocument;

packages/fxa-settings/src/components/DropDownAvatarMenu/index.test.tsx:64:    expect(dropDown).toBeInTheDocument;
packages/fxa-settings/src/components/DropDownAvatarMenu/index.test.tsx:95:    expect(dropDown).toBeInTheDocument;
packages/fxa-settings/src/components/DropDownAvatarMenu/index.test.tsx:113:    expect(dropDown).toBeInTheDocument;
```

2022-05-20 15:15 UTC, LZoog commented
@pdehaan Running CI now. When you see it passes, do you mind fixing up your previous commit so there's only one that will be merged? When you force push CI won't run again but that's fine, will r+/merge and close #12965

2022-05-20 15:37 UTC, LZoog commented
@pdehaan I think you need to rebase against `main` for CI to get the `sr-LATN` fix. Do you mind rebasing & squashing your commits, and then I'll pull that commit into that other branch?

Sorry this is turning into so much trouble for what this fixes 🤣

2022-05-20 22:21 UTC, LZoog approved these changes
@pdehaan Will you file that follow up to fix the tests that failed? Thank you! 🙏

2022-05-20 22:21 UTC, merged

2022-05-21 15:45 UTC, pdehaan commented
> @pdehaan Will you file that follow up to fix the tests that failed? Thank you! 🙏

Filed as https://github.com/mozilla/fxa/issues/12978