copy(fxa-auth-server): update copy for verifyShortCode email
mozilla/fxa pull request #13887
Opened 2022-08-04 20:47 UTC by millsoper

## Because

- We want to update copy for verification/confirmation emails

## This pull request

- Updates strings and adds a new translation string to match the new given copy

## Issue that this pull request solves

Closes: # n/a

## Checklist

_Put an `x` in the boxes that apply_

- [x] My commit is GPG signed.
- [x] If applicable, I have modified or added tests which pass locally.
- [ ] I have added necessary documentation (if appropriate).
- [ ] I have verified that my changes render correctly in RTL (if appropriate).

## Screenshots (Optional)

<img width="992" alt="Screen Shot 2022-08-04 at 1 45 06 PM" src="https://user-images.githubusercontent.com/11150372/182949263-cd3f0aad-a2b8-4b53-92e9-00974908696f.png">

## Other information (Optional)

To see the changes, `cd` into the fxa-auth-server directory and run `yarn storybook`.

This PR actually only has one commit, but is on top of my prior copy PR (and will be rebased onto main once that's merged.)

2022-08-04 22:34 UTC, bcolsson requested changes

2022-08-04 22:34 UTC, bcolsson commented on packages/fxa-auth-server/lib/senders/emails/templates/verifyShortCode/en.ftl
> +verifyShortCode-title-subtext = Confirm your account and get the most out of Firefox everywhere you sign in starting with:
```suggestion
# Information on the browser and device triggering this confirmation email follows below this string.
verifyShortCode-title-subtext = Confirm your account and get the most out of { -brand-firefox } everywhere you sign in starting with:
```
Suggest adding a comment about what will displayed after "starting with:" for context.
Please use brand placeholder here too.

2022-08-12 18:20 UTC, chenba commented
Is this PR ready for review again?

2022-08-15 14:06 UTC, xlisachan approved these changes
r+, just a nit in the index.txt.

2022-08-15 18:18 UTC, bcolsson approved these changes

2022-08-15 18:19 UTC, merged