feat(metrics): Expand the metrics that are stored during upgrades
mozilla/fxa pull request #13968
Opened 2022-08-18 20:12 UTC by xlisachan

## Because

- the product and price change when upgrading products 

## This pull request

- adds `previous_plan_id`, `previous_plan_id`, and `utm_referrer`

## Checklist

_Put an `x` in the boxes that apply_

- [x] My commit is GPG signed.
- [x] If applicable, I have modified or added tests which pass locally.

2022-08-22 18:56 UTC, StaberindeZA requested changes
When testing this locally I noticed the following.
- In the browser `utm_referrer` was part of the call to `POST /v1/metrics`. However `previousPlanId` and `previousProductId` were not.
  - Doesn't look like these values are passed into the function.
- In the payments-server logs, it doesn't look like any of the new fields are in the `amplitudeEvent` log.
  - Since these are all new fields, we'll need to add a custom `EVENT_PROPERTIES` mapper in `fxa-shared/metrics/amplitude.js`. That should fix this issue.

2022-08-22 20:20 UTC, pdehaan commented on packages/fxa-payments-server/src/lib/apiClient.ts
> +  utmReferrer?: string;
Is this used somewhere? I think this is the only reference to `utmReferrer` in this PR.

2022-08-26 22:11 UTC, StaberindeZA requested changes
Nice! Looks like, `previous_plan_id`, `previous_product_id` and `utm_referrer` are all in the call to `POST /metrics`.

`utm_referrer` also shows up in the stdout log. Unfortunately, `previous_plan_id` and `previous_product_id` are not.
```
28|payments  | 2022-08-26T18:04:47: INFO fxa-payments-server.amplitudeEvent: {"op":"amplitudeEvent","event_type":"fxa_pay_upgrade - submit","time":1661551487121,"user_id":"7052485a9b714b90af5c0191529b965b","device_id":"505c43468ed64017be6291dac80a1a87","session_id":1661549765458,"app_version":"239.0","os_name":"Mac OS X","os_version":"10.15","event_properties":{"plan_id":"price_1KbomlBVqmGyQTMaa0Tq7UaW","product_id":"prod_GqM9ToKK62qjkK","payment_provider":"stripe"},"user_properties":{"flow_id":"0c19bc65465edc5fd0377e446feb077794894f846a0612f30098a4b63fd3e957","ua_browser":"Firefox","ua_version":"105.0","utm_referrer":"okwhatnow"}}
```

I think you'll need to add a mapping function to `EVENT_PROPERTIES` in `fxa-shared/metrics/amplitude.js` line 66.

2022-08-29 13:03 UTC, xlisachan commented
Got it! I had my parameters in the wrong order in a couple of the files 🤦🏻‍♀️

```
28|payments  | 2022-08-29T09:00:50: INFO fxa-payments-server.amplitudeEvent: {"op":"amplitudeEvent","event_type":"fxa_pay_upgrade - success","time":1661778050089,"user_id":"9ac4634ed984409cbb6db5e132c5577e","device_id":"648ff217c8f8415182a11c532319b344","session_id":1661778033639,"app_version":"239.0","os_name":"Mac OS X","os_version":"10.15","event_properties":{"plan_id":"price_1KbomlBVqmGyQTMaa0Tq7UaW","product_id":"prod_GqM9ToKK62qjkK","previous_plan_id":"plan_GqM9N6qyhvxaVk","previous_product_id":"prod_GqM9ToKK62qjkK","payment_provider":"stripe"},"user_properties":{"flow_id":"feeadf1588cfe22ed36a48cc2af0bb89300bafee597c099acfb78ad1cdf3e41d","ua_browser":"Firefox","ua_version":"103.0"}}
```

2022-08-29 16:19 UTC, StaberindeZA commented
> Got it! I had my parameters in the wrong order in a couple of the files 🤦🏻‍♀️
> 
> ```
> 28|payments  | 2022-08-29T09:00:50: INFO fxa-payments-server.amplitudeEvent: {"op":"amplitudeEvent","event_type":"fxa_pay_upgrade - success","time":1661778050089,"user_id":"9ac4634ed984409cbb6db5e132c5577e","device_id":"648ff217c8f8415182a11c532319b344","session_id":1661778033639,"app_version":"239.0","os_name":"Mac OS X","os_version":"10.15","event_properties":{"plan_id":"price_1KbomlBVqmGyQTMaa0Tq7UaW","product_id":"prod_GqM9ToKK62qjkK","previous_plan_id":"plan_GqM9N6qyhvxaVk","previous_product_id":"prod_GqM9ToKK62qjkK","payment_provider":"stripe"},"user_properties":{"flow_id":"feeadf1588cfe22ed36a48cc2af0bb89300bafee597c099acfb78ad1cdf3e41d","ua_browser":"Firefox","ua_version":"103.0"}}
> ```

@xlisachan I tested it locally and the previous product/plan ID is still not showing up for me. Did you get it working on your end without needing to add the mapping function to `EVENT_PROPERTIES` in `fxa-shared/metrics/amplitude.js` line 66.

2022-08-29 18:04 UTC, StaberindeZA approved these changes
LGTM. Thanks for the changes

2022-08-29 18:28 UTC, xlisachan commented
Weird that it showed up in my logs before mapping - thanks for guiding me through this and for the thorough review, @StaberindeZA! I really appreciate it :)

2022-08-29 18:28 UTC, merged