fix(CAD): Don't redirect from CAD page to pair from menu > sign in
mozilla/fxa pull request #14082
Opened 2022-09-08 22:18 UTC by LZoog

Because:
* Browser menu > Sign in and Sync should show the connect another device screen and not immediately take users to the the /pair page

This commit:
* Adds a check for 'action=email' and doesn't redirect if present with 'entrypoint=fxa_app_menu'

Closes [FXA-5850](https://mozilla-hub.atlassian.net/browse/FXA-5850)

---

See ticket and see [this comment](https://mozilla-hub.atlassian.net/browse/FXA-5452?focusedCommentId=573894). I tested most of the flows laid out, but there's a lot, so feel free to poke around.

2022-09-09 21:45 UTC, dschom commented
@LZoog The changes look fine, and I've validated them locally. The `Browser menu > Sign in and Sync` shows the `/connect_another_device` like it used to prior to FXA-5452.

I did notice, that there are several 'Sign in and Sync' flows though. Here's a comprehensive list of the flows and their current behaviors:

- `Browser menu > Sign in and Sync`
  - Directs to `signin?context=fx_desktop_v3&entrypoint=fxa_app_menu&action=email&service=sync`
  - Results in  `/connect_another_device` screen
- `Show Side Bar > Synced Tabs > Sign in to Sync` 
  - Directs to `signin?context=fx_desktop_v3&entrypoint=tabs-sidebar&action=email&service=sync`
  - Results in `/pair`  screen
- `Show tabs from other devices > Sign in to Sync` 
  - Directs to `signin?context=fx_desktop_v3&entrypoint=synced-tabs&action=email&service=sync`
  - Results in`/pair` screen
- `about:preferences#sync > Sign in to sync` --> Still redirects to `/pair`
  - Directs to `/signin?context=fx_desktop_v3&entrypoint=preferences&action=email&service=sync`
  - Results in `/pair` screen

If you feel these behaviors are correct I can r+; however, it seems like all these `sign in to sync` flows should be consistent. 

By the way, the above flows were called out during QA and validated when I was initially working on FXA-5452. It feels like we are undoing part of what was requested in FXA-5452. Was this change run by product? I will say showing the `/connect_another_device` screen feels more natural, but we might be undermining the intent of FXA-5452 which was: 

> "As a Firefox desktop user, I want the FxA flow to give me the option to easily “download Firefox mobile” in case I don’t have it already"

2022-09-09 21:49 UTC, dschom requested changes
Changes look good and work as intended. I can r+, but I'd like you to confirm the state of the other `sign in to sync` flows first. See comment above.

2022-09-12 20:53 UTC, LZoog commented
@dschom This change was requested by product because it was identified as a bug, but, I think we might need to sync up with Vesta to double check, because now I'm a bit confused on intended behavior. I'll set up a quick meeting for us, thanks for spelling all that out. 👍

2022-09-13 18:39 UTC, LZoog commented
@dschom It looked to me like we wanted to keep `FIREFOX_MENU_ENTRYPOINT` around because Browser > Account > Connect Another Device takes users to CAD through that entrypoint, so I left the `action=email` differentiator there. Let me know if you see any edgecases missed. (Btw, I'll leave a comment for QA on this ticket after we close it since it's kind of evolved.)

 I went ahead and fixed FXA-5947 here too because I was in related files and we'd just talked about it.

2022-09-13 22:16 UTC, dschom commented
@LZoog I've run through a few scenarios. Most look good. There seems to be a discrepancy in 'connect another device' flows. 

For example, sign into fxa, and then compare the following behaviors. `Browser Menu > signed-in account name > Connect Another Device` vs. `Side Bar > Synced Tabs > Connect Another Device`

2022-09-14 01:05 UTC, dschom approved these changes

2022-09-14 15:41 UTC, LZoog commented
@dschom Thanks for going through the flows and pointing that out, `Side Bar > Synced Tabs > Connect Another Device` is one I did not test. I know you know this but the other way to hit that page is here which does go to `/pair`:
![image](https://user-images.githubusercontent.com/13018240/190197287-9fdc99f0-c5dd-41d3-a023-8c5a31311db9.png)

I've [filed a follow up ticket for this](https://mozilla-hub.atlassian.net/browse/FXA-5952), I think it's going to be a 1 pointer accounting for the `tabs-sidebar` entrypoint but I'd want to make sure any login/registration flows using that entrypoint still takes the user to `connect_another_device`.

2022-09-14 15:42 UTC, merged