copy(fxa-auth-server): update postAddTwoStepAuthentication email copy
mozilla/fxa pull request #14182
Opened 2022-09-29 23:29 UTC by millsoper

## Because:

* We're updating email copy

## This commit:

* Update copy, tests, and fluent files for postAddTwoStepAuthentication email

## Closes # https://mozilla-hub.atlassian.net/browse/FXA-5195

## Checklist

_Put an `x` in the boxes that apply_

- [x] My commit is GPG signed.
- [x] If applicable, I have modified or added tests which pass locally.
- [ ] I have added necessary documentation (if appropriate).
- [ ] I have verified that my changes render correctly in RTL (if appropriate).

## Screenshots (Optional)

<img width="924" alt="Screen Shot 2022-09-29 at 4 27 33 PM" src="https://user-images.githubusercontent.com/11150372/193159601-61988b31-63c6-4275-a560-daea1607c9a0.png">

2022-10-03 20:37 UTC, bcolsson approved these changes

2022-10-04 15:51 UTC, dschom requested changes
One minor nitpick, there appear to be new lines missing in the plain text. Please fix this before merging. Other than this it looks good 👍 .

<img width="355" alt="image" src="https://user-images.githubusercontent.com/94418270/193865905-49311cee-7b2b-4b5f-bb2c-c1e25d66fa55.png">.

By the way, I think you have provided a screen shot of a different template by accident.

2022-10-04 17:05 UTC, flodolo commented on packages/fxa-auth-server/lib/senders/emails/templates/postAddTwoStepAuthentication/en.ftl
> +postAddTwoStepAuthentication-subject-2 = Two-step authentication turned-on
This should probably be without an hyphen
https://www.merriam-webster.com/dictionary/turned-on

2022-10-04 20:25 UTC, millsoper commented
> One minor nitpick, there appear to be new lines missing in the plain text. Please fix this before merging. Other than this it looks good 👍 .
> 
> <img alt="image" width="355" src="https://user-images.githubusercontent.com/94418270/193865905-49311cee-7b2b-4b5f-bb2c-c1e25d66fa55.png">.
> 
> By the way, I think you have provided a screen shot of a different template by accident.

Good idea! Updated and thank you!

2022-10-07 18:50 UTC, dschom approved these changes
LGTM!

2022-10-07 19:31 UTC, merged