test(functional): rewrite password tests using playwright
mozilla/fxa pull request #14486
Opened 2022-11-16 21:44 UTC by ashrivastava-qa

## Because

-

## This pull request

-

## Issue that this pull request solves

Closes: # (issue number)

## Checklist

_Put an `x` in the boxes that apply_

- [ ] My commit is GPG signed.
- [ ] If applicable, I have modified or added tests which pass locally.
- [ ] I have added necessary documentation (if appropriate).
- [ ] I have verified that my changes render correctly in RTL (if appropriate).

## Screenshots (Optional)

Please attach the screenshots of the changes made in case of change in user interface.

## Other information (Optional)

Any other information that is important to this pull request.

2022-11-17 00:07 UTC, pdehaan commented on packages/functional-tests/pages/login.ts
> +      //await error3.waitFor({ state: "visible" });
What is this doing?
IIUC, wouldn't `allErrors` return an array w/ 3 Booleans, like `[true, true, true]`?
And then below we do:

```js
expect(await login.emptyOrShortPasswordError()).toBeTruthy();
```

Which would potentially convert to:

```js
expect([true, true, true]).toBeTruthy();
```

Doing some light testing outside Playwright, I'm not sure what's a happenin':

```js
const arr = Promise.resolve([false, false, false]);

test("things", async () => {
  expect(await arr).toBeTruthy();
});
```

```
> jest

 PASS  ./index.test.js
  ✓ things

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        0.162 s, estimated 1 s
Ran all test suites.
```

So `[false, false, false]` still seems to pass the test.

---

If we want to assert _all_ values in the array are `true` (or `false`), we can use `.filter()` and `.toHaveLength()`:

```js
const arr = Promise.resolve([false, false, false]);

test("things", async () => {
  let arr2 = await arr;
  arr2 = arr2.filter(Boolean);
  expect(arr2).toHaveLength(0);
});
```

Or if you want _at least one_ truthy value, maybe even something like `.toBeGreaterThan(0)`.

2022-11-17 16:41 UTC, ashrivastava-qa commented on packages/functional-tests/pages/login.ts
> +  MIN_LENGTH_MET: '#password-too-short.password-strength-met',
Yes! That's why I tried to keep all the `*MET` and `*FAIL` together, for it to be more readable.

2022-11-17 16:51 UTC, ashrivastava-qa commented on packages/functional-tests/tests/settings/password.spec.ts
> +      await login.submit();
that's just a `beforeEach()` hook to provide email and submit. No assertion is happening there, so no `expect()` is needed.

2022-11-17 16:51 UTC, ashrivastava-qa commented on packages/functional-tests/tests/settings/password.spec.ts
> +  test('good password, then back to too short ', async ({
Fixing it now. Thanks!

2022-11-17 16:57 UTC, ashrivastava-qa commented on packages/functional-tests/tests/settings/password.spec.ts
> +  test.beforeEach(
The `beforEach()` is creating the sync email id, redirecting to the url and then providing the email in the textbox and submitting. But the tests are submitting the different passwords and taking it from there to check for validations. Though everytime its creating a different account.

2022-11-17 21:16 UTC, vbudhram commented on packages/functional-tests/tests/settings/password.spec.ts
> +    await login.submitButton.click();
@ashrivastava-qa Iets go with putting it into one test block, in my local testing it saves 10seconds.

<img width="1030" alt="Screen Shot 2022-11-17 at 4 09 11 PM" src="https://user-images.githubusercontent.com/1295288/202561412-d0069779-12b7-4119-9094-2506e1b30310.png">

vs

<img width="771" alt="Screen Shot 2022-11-17 at 4 12 06 PM" src="https://user-images.githubusercontent.com/1295288/202561377-d22f668f-b449-4367-a121-e9b7eca3d5cf.png">

2022-11-17 21:18 UTC, vbudhram commented on packages/functional-tests/tests/settings/password.spec.ts
> +  test.beforeEach(
Ah gotcha 👍🏽

2022-11-17 21:19 UTC, vbudhram commented on packages/functional-tests/tests/settings/password.spec.ts
> +      const email = login.createEmail('sync{id}');
I think you can created a regular email and not use sync. Also, you should be able to load the default page via

```
await page.goto(target.contentServerUrl, { waitUntil: 'networkidle' });
```

2022-11-17 21:21 UTC, vbudhram requested changes
@ashrivastava-qa LGTM, only thing is to combine into one test block.

2022-11-21 15:32 UTC, ashrivastava-qa commented on packages/functional-tests/pages/login.ts
> +      //await error3.waitFor({ state: "visible" });
created different async functions for all the selectors.

2022-11-21 17:09 UTC, pdehaan approved these changes

2022-11-23 15:21 UTC, vbudhram approved these changes
@ashrivastava-qa Thank you!

2022-11-23 15:22 UTC, merged