feat(payments): move The Confirmation Checkbox
mozilla/fxa pull request #15092
Opened 2023-03-28 05:35 UTC by IvoJP

Because:

* the confirmation checkbox looks like it applies to just the paypal payment option and confuses users since the submit payment is disabled until checked

This Commit:

* moves the checkbox, adds info about the price and product the user is committing to

Closes: FXA-4260

## Checklist

_Put an `x` in the boxes that apply_

- [ ] My commit is GPG signed.
- [ ] If applicable, I have modified or added tests which pass locally.
- [ ] I have added necessary documentation (if appropriate).
- [ ] I have verified that my changes render correctly in RTL (if appropriate).

## Screenshots (Optional)

Please attach the screenshots of the changes made in case of change in user interface.

## Other information (Optional)

Any other information that is important to this pull request.

2023-03-28 16:45 UTC, sardesam reviewed
Changes look good! Tested in LTR, on both Fx and Chrome, and mobile.

Before I can approve, two quick things to verify with @marniepw @chelsea-lewis @stefopsal

1. Nit: I thought the copy had changed for `First you'll need to approve your subscription`? Please confirm.

2. From [this Jira comment](https://mozilla-hub.atlassian.net/browse/FXA-4260?focusedCommentId=656539) it looks like the original intention is to be able to tab or click on the disabled `Subscribe Now` button and the error tooltip pops up? Or was the tooltip only a nice to have if it were possible?

@IvoJP how much effort would it be to make (2) happen? My only concern is that there's no indication to alert the customer that they missed checking the box.

Additional Notes:

- Discussed and investigated with @IvoJP there is additional work that would need to be done in order to really make this page accessible. It falls out of scope of this ticket. I recommend filing a follow up ticket to address it.
- Identified a pre-existing (design/UX) issue. On mobile, if either the form wasn't filled out (sign in to new account) or the box isn't checked and the customer is scrolled to the bottom, after filling out CC details, the customer is unaware of which portions of the form haven't been filled out. They are not redirected and would have to scroll back up on their own.

2023-03-28 17:39 UTC, bcolsson requested changes

2023-03-28 17:39 UTC, bcolsson commented on packages/fxa-payments-server/src/components/PaymentMethodHeader/en.ftl
> +payment-method-first-approve = First you'll need to approve your subscription
```suggestion
payment-method-first-approve = First you’ll need to approve your subscription
```
Please use typographic quotes for text.

2023-03-28 17:39 UTC, bcolsson commented on packages/fxa-payments-server/src/routes/en.ftl
> +pay-with-heading-paypal = Pay with PayPal
```suggestion
pay-with-heading-paypal = Pay with { -brand-name-paypal }
```

Please use brand terms instead of hard coding.

2023-03-28 17:39 UTC, bcolsson commented on packages/fxa-payments-server/src/components/PaymentConsentCheckbox/en.ftl
> +payment-confirm-with-legal-links = I authorize { -brand-name-mozilla }, maker of { -brand-name-firefox } products, to charge my payment method {$price} for {$productName}, according to <termsOfServic
```suggestion
# Variables: $price (String) - The amount of the subscription being billed, including currency, e.g. $10.00. 
# $productName (String) - The name of the subscribed product, e.g. Mozilla VPN.
payment-confirm-with-legal-links = I authorize { -brand-name-mozilla }, maker of { -brand-name-firefox } products, to charge my payment method { $price } for { $productName }, according to <termsOfServiceLink>Terms of Service</termsOfServiceLink> and <privacyNoticeLink>Privacy Notice</privacyNoticeLink>, until I cancel my subscription.
```
Please include information in comments for what and how variables will be rendered in the string.
Variables in fluent should also have a space before and after the variable name within the brackets.

2023-03-28 20:13 UTC, IvoJP commented
@bcolsson merged and squashed your changes

2023-03-28 20:34 UTC, sardesam approved these changes
After checking with @clewis, this ticket is good to go. Accessibility concerns and tooltip error will be filed and addressed in a follow-up ticket.

2023-03-29 16:04 UTC, merged

2023-03-31 05:48 UTC, bcolsson commented on packages/fxa-payments-server/src/components/PaymentMethodHeader/en.ftl
> +payment-method-first-approve = First you'll need to approve your subscription
@IvoJP 
It looks like t[his commit](https://github.com/mozilla/fxa/compare/24510c38c356cfc4cf225547495e071937d5f4c2..32a290a1d60a0f1a9daba310bd1e0e0b00590a81) reverted this change. Can you push a PR with this fix before I expose this string for translation?
```payment-method-first-approve = First you’ll need to approve your subscription```