WIP/DRAFT test(functional-tests) - Update recoveryKey tests for new flow
mozilla/fxa pull request #15333
Opened 2023-05-18 20:38 UTC by vpomerleau

WIP - rebased on https://github.com/mozilla/fxa/pull/15299/

## Because

- We need to update functional tests to support the new account recovery key creation flow

## This pull request

- Update the recovery key page model
- Update `misc`, `password` and `recoveryKey` tests behind feature flag
- TODO : update `react-conversion` tests

## Issue that this pull request solves

Closes: #FXA-7250

## Checklist

_Put an `x` in the boxes that apply_

- [ ] My commit is GPG signed.
- [ ] If applicable, I have modified or added tests which pass locally.
- [ ] I have added necessary documentation (if appropriate).
- [ ] I have verified that my changes render correctly in RTL (if appropriate).

## Screenshots (Optional)

Please attach the screenshots of the changes made in case of change in user interface.

## Other information (Optional)

Any other information that is important to this pull request.

2023-05-19 17:45 UTC, vpomerleau commented on packages/fxa-settings/src/components/Settings/UnitRowRecoveryKey/index.tsx
> +  );
This was corrected in the PR this was originally rebased on, should be good now.

2023-05-23 19:22 UTC, ashrivastava-qa commented
@vpomerleau I have not been able to run the new tests, when I run the tests with the feature flag set to true, I still see the old tests running.

2023-05-23 21:06 UTC, ashrivastava-qa commented
Okay so we found out that adding the featureFlag to only `local.json-dist` file doesn't work and needs to be added to `local.json` file too.

2023-05-23 21:06 UTC, ashrivastava-qa requested changes

2023-05-23 21:18 UTC, vpomerleau commented on packages/functional-tests/tests/settings/misc.spec.ts
> +    if (config.featureFlags.showRecoveryKeyV2 !== true) {
My thought here was that we might want to entirely remove this test once we phase out the old flow - the download/copy/print functions have changed in the new flow - only "copy" is still part of that "dataTrio" component, the "print" is entirely removed, and "download" is part of a separate download CTA button. To make sure we keep testing these functions, I've added a test case to the main "recoveryKey" test file (I'll add a comment there).

So... if featureFlag is true, there is nothing to test here. Let me know if that makes sense or if we want to specifically test those functions in a smoke test too.

2023-05-23 21:18 UTC, vpomerleau commented on packages/functional-tests/tests/settings/recoveryKey.spec.ts
> +  test('can copy and download recovery key', async ({
New copy/download test is here @ashrivastava-qa

2023-05-23 23:00 UTC, vpomerleau commented
@ashrivastava-qa I checked the CI test results, and FWIW it's only testing the new account recovery key flow.  I can tell from the output because "can copy and download recovery key" is a new test that only runs if the feature flag is true.

![image](https://github.com/mozilla/fxa/assets/22231637/8a63fe98-15e0-4615-924c-5d197590ba9a)

It might be a problem that only the new flow is running considering that we will continue to have the old flow up in production until the new one passes QA, but I'm not entirely sure how to rework the tests to run tests for both flows (feature flag on or off). 

@dschom would you have some suggestions about how we can make sure tests run on CI for both values (true/false) of FEATURE_FLAGS_SHOW_RECOVERY_KEY_V2?

2023-05-24 00:58 UTC, dschom commented
@vpomerleau This should be doable. I think something like [this](https://github.com/mozilla/fxa/pull/15363/commits/771491e6f59e90ef74401e97fede97465a6e1efa) would work.

2023-05-24 01:26 UTC, vpomerleau commented
@dschom Sweet, I'll give that a try. Right now the playwright tests are pulling directly from the content server config, and the feature flag is only enabled in dev with`local.json-dist`.

Do the checks on PRs only test for dev environment, or would they also check for stage and production environments? Wondering if the var change will only be picked up when we run deploy tests.

2023-05-24 14:52 UTC, ashrivastava-qa commented
@vpomerleau the PR checks run for dev/local env only.

2023-05-24 14:53 UTC, ashrivastava-qa approved these changes
LGTM :)

2023-05-24 15:23 UTC, merged