task(payments): Update strings referencing 'Firefox accounts'
mozilla/fxa pull request #15810
Opened 2023-09-19 00:21 UTC by dschom

## Because

- We want to start the localization effort of updating strings from Firefox to Mozilla

## This pull request

- Creates new l10n strings / ids using the Mozilla branding

## Issue that this pull request solves

Closes: FXA-7991

## Checklist

_Put an `x` in the boxes that apply_

- [x] My commit is GPG signed.
- [ ] If applicable, I have modified or added tests which pass locally.
- [ ] I have added necessary documentation (if appropriate).
- [ ] I have verified that my changes render correctly in RTL (if appropriate).

## Screenshots (Optional)

Please attach the screenshots of the changes made in case of change in user interface.

## Other information (Optional)

Any other information that is important to this pull request.

2023-09-19 22:28 UTC, bcolsson requested changes

2023-09-19 22:28 UTC, bcolsson commented on packages/fxa-payments-server/src/components/NewUserEmailForm/en.ftl
> +new-user-sign-in-link-2 = Already have a { -brand-name-mozilla } account? <a>Sign in</a>
```suggestion
new-user-sign-in-link-2 = Already have a { -product-mozilla-account }? <a>Sign in</a>
```
Best to update this string to use the correct term here.

2023-09-19 22:28 UTC, bcolsson commented on packages/fxa-payments-server/src/routes/Checkout/en.ftl
> +new-user-step-1-2 = 1. Create a { -brand-name-mozilla } account
```suggestion
new-user-step-1-2 = 1. Create a { -product-mozilla-account }
```

2023-09-21 02:42 UTC, sardesam approved these changes
r+ from me but I do have a question.

`-product-mozilla-account` and `-product-mozilla-account` (edit: `-product-firefox-account`) are both declared in `packages/fxa-shared/l10n/branding.ftl` with the former replacing `-brand-name-firefox` in `NewUserEmailForm` and `routes/Checkout`. However, `packages/fxa-shared/l10n/branding.ftl` has `-brand-mozilla` and `-brand-firefox`, yet we're using `-brand-name-mozilla` and `-brand-name-firefox` defined in `packages/fxa-payments-server/src/branding.ftl` instead.

I'm curious why it's structured this way. Should we keep as is or update to use the shared branding file instead?

Note: three additional files and six translations - five for `-brand-name-mozilla` and one for `-brand-name-firefox` - would be affected.

Edit: typos. I know it's been quote replied twice now, but correcting for future reference to anyone reading.

2023-09-21 18:04 UTC, dschom commented
> r+ from me but I do have a question.
> 
> `-product-mozilla-account` and `-product-mozilla-account` are both declared in `packages/fxa-shared/l10n/branding.ftl` with the former replacing `-brand-name-firefox` in `NewUserEmailForm` and `routes/Checkout`. However, `packages/fxa-shared/l10n/branding.ftl` has `-brand-mozilla` and `-brand-firefox`, yet we're using `-brand-name-mozilla` and `-brand-name-firefox` defined in `packages/fxa-payments-server/src/branding.ftl` instead.
> 
> I'm curious why it's structured this way. Should we keep as is or update to use the shared branding file instead?
> 
> Note: three additional files and six translations - five for `-brand-name-mozilla` and one for `-brand-name-firefox` - would be affected.

Good catch. I'd say we should be using the branding file in fxa-shared... Let me look into this.

2023-09-21 21:13 UTC, bcolsson commented
> > r+ from me but I do have a question.
> > `-product-mozilla-account` and `-product-mozilla-account` are both declared in `packages/fxa-shared/l10n/branding.ftl` with the former replacing `-brand-name-firefox` in `NewUserEmailForm` and `routes/Checkout`. However, `packages/fxa-shared/l10n/branding.ftl` has `-brand-mozilla` and `-brand-firefox`, yet we're using `-brand-name-mozilla` and `-brand-name-firefox` defined in `packages/fxa-payments-server/src/branding.ftl` instead.
> > I'm curious why it's structured this way. Should we keep as is or update to use the shared branding file instead?
> > Note: three additional files and six translations - five for `-brand-name-mozilla` and one for `-brand-name-firefox` - would be affected.
> 
> @sardesam Good catch. I'd say we should be using the branding file in [fxa-shared](https://mozilla-hub.atlassian.net/browse/FXA-shared)... Let me look into this.

@sardesam - Good catch. Yes, I'd recommend using brands from `branding.ftl` going forward. Last year some work went into making a shared branding file so for historical reasons, older strings are using different term IDs that only exist in `payments.ftl`.

2023-09-21 21:14 UTC, bcolsson commented on packages/fxa-payments-server/src/components/Header/en.ftl
> +brand-name-mozilla-logo = { -brand-name-mozilla } logo
```suggestion
brand-name-mozilla-logo = { -brand-mozilla } logo
```

2023-09-21 22:44 UTC, dschom commented
@bcolsson @sardesam I am looking at the [grunt.js](https://github.com/mozilla/fxa/blob/8ccf65de04956a64f2b9d4386ad08f4edf47a8d0/packages/fxa-payments-server/Gruntfile.js#L7) file in fxa-payments. Sounds like in order to use the branding file in fxa-shared I'd need to alter the grunt file and from that comment it sounds like this could potentially introduce conflicts in l10n strings. 

Because of this, I am thinking we should just stick with what is available in fxa-payments-server. Let me know what you think. If you all think we should go for it, I am happy to do so, but I'd mostly just like to get these changes landed and limit any possible side effects.

2023-09-21 23:50 UTC, bcolsson commented
@dschom - it looks like we're already using `{ -brand-mozilla }` in some strings.

This is getting deep into how FxA bundles and uses strings, so I'm not 100% sure I fully understand it, but this [PR](https://github.com/mozilla/fxa/pull/15535) seems like it may have resolved the issue?

2023-09-21 23:57 UTC, bcolsson commented
Although trying to test if these terms work in storybook I'm getting an error for the [NewUserEmailForm](https://storage.googleapis.com/mozilla-storybooks-fxa/commits/latest/fxa-payments-server/index.html?path=/story/components-newuseremailform--default):

2023-09-25 21:25 UTC, dschom commented
> This is getting deep into how FxA bundles and uses strings, so I'm not 100% sure I fully understand it, but this https://github.com/mozilla/fxa/pull/15535 seems like it may have resolved the issue?

I don't think that's the case. I believe that PR actually **removed** the reference to the shared branding file in order to avoid l10n id conflicts. See diff [here](https://github.com/mozilla/fxa/pull/15535/files#r1336403374).

2023-09-25 21:26 UTC, dschom commented
> Although trying to test if these terms work in storybook I'm getting an error for the [NewUserEmailForm](https://storage.googleapis.com/mozilla-storybooks-fxa/commits/latest/fxa-payments-server/index.html?path=/story/components-newuseremailform--default):

@bcolsson This appears to be an existing issue, but I think it'll be easy enough to fix. I'll push a change shortly.

2023-09-26 17:05 UTC, sardesam commented
> > Although trying to test if these terms work in storybook I'm getting an error for the [NewUserEmailForm](https://storage.googleapis.com/mozilla-storybooks-fxa/commits/latest/fxa-payments-server/index.html?path=/story/components-newuseremailform--default):
> 
> @bcolsson This appears to be an existing issue, but I think it'll be easy enough to fix. I'll push a change shortly.

As per my chat with @dschom. I'll take care of this. `PaymentProcessing` is also affected.

2023-09-27 00:44 UTC, dschom commented
@bcolsson I've updated the strings, so that the reference are in line with the`fxa-shared/l10n/branding.ftl` file. @sardesam is looking into the issue with story book. I'll rebase as soon as here change lands and let you know.

2023-09-27 15:28 UTC, sardesam commented
> @bcolsson I've updated the strings, so that the reference are in line with the`fxa-shared/l10n/branding.ftl` file. @sardesam is looking into the issue with story book. I'll rebase as soon as here change lands and let you know.

Storybook issue: https://github.com/mozilla/fxa/pull/15842

2023-09-27 16:05 UTC, sardesam approved these changes
r+

2023-09-27 17:21 UTC, bcolsson approved these changes

2023-09-27 17:21 UTC, bcolsson commented on packages/fxa-payments-server/src/components/Header/en.ftl
> +brand-name-mozilla-logo = { -brand-mozilla } logo
Based on Storybook it appears terms from `shared/branding.ftl` are working with payments as well.

2023-09-27 17:33 UTC, merged