fix(payments): config file missing in build
mozilla/fxa pull request #15886
Opened 2023-10-09 14:41 UTC by StaberindeZA

## Because

- payments-next heartbeat api returns 500 due to missing config file.

## This pull request

- Reorders nest-typed-config loaders so that fileLoader is first, which results in an empty .env.json file to be included in the payments-next build.
- Adds normalization step to config loader, for non-string values.

## Issue that this pull request solves

Closes: #

## Checklist

_Put an `x` in the boxes that apply_

- [x] My commit is GPG signed.
- [x] If applicable, I have modified or added tests which pass locally.
- [x] I have added necessary documentation (if appropriate).
- [x] I have verified that my changes render correctly in RTL (if appropriate).

2023-10-09 20:26 UTC, bbangert requested changes
This add's back convict, which we are trying to leave behind.

2023-10-09 21:59 UTC, StaberindeZA commented
> This add's back convict, which we are trying to leave behind.

Ah cool! Yup I think I missed this. I've removed the commit that adds `convict`.

2023-10-09 23:15 UTC, bbangert approved these changes

2023-10-10 15:28 UTC, merged

2023-10-10 15:30 UTC, StaberindeZA commented
This is the [related SRE PR](https://github.com/mozilla-it/webservices-infra/pull/1037) that updates the environment variables.