test(functional): Disable failing test on stage
mozilla/fxa pull request #15891
Opened 2023-10-10 00:06 UTC by xlisachan

## Because

- it was observed that this test failed on stage env

## This pull request

- disables the test until it is fixed

## Checklist

_Put an `x` in the boxes that apply_

- [x] My commit is GPG signed.

2023-10-10 12:38 UTC, ashrivastava-qa commented
Just one comment, please add a comment with the ticket number created as a reason for disabling the test. Something like [this](https://github.com/mozilla/fxa/blob/main/packages/functional-tests/tests/react-conversion/signup.spec.ts#L79)

2023-10-10 12:40 UTC, ashrivastava-qa requested changes

2023-10-10 12:40 UTC, ashrivastava-qa commented on packages/functional-tests/tests/subscription-tests/subscription.spec.ts
> +      // test('New user checkout URL to have RP-provided flow params, acquisition params & verify funnel metrics', async ({
Please add a comment here with the created jira ticket no. Something like "Disabling the test until FXA-XXXX is fixed"

2023-10-10 12:40 UTC, ashrivastava-qa commented on packages/functional-tests/tests/subscription-tests/subscription.spec.ts
> +      // test('New user checkout URL to have RP-provided flow params, acquisition params & verify funnel metrics', async ({
nit : instead of using // for every line, you could use /*...*/

2023-10-10 15:55 UTC, ashrivastava-qa approved these changes

2023-10-10 15:56 UTC, ashrivastava-qa commented
Thank @xlisachan for working on this! :)

2023-10-10 19:41 UTC, merged

2023-10-11 00:23 UTC, pdehaan commented on packages/functional-tests/tests/subscription-tests/subscription.spec.ts
> +      /* Disabling test - to fix in FXA-8447
@ashrivastava-qa Not sure if you want to do a followup PR to convert to [`.fixme()`](https://playwright.dev/docs/api/class-test#test-fixme-2) or [`.skip()`](https://playwright.dev/docs/api/class-test#test-skip-2) annotations instead so these are easier to track and reenable in the future.
https://playwright.dev/docs/test-annotations#skip-a-test