bug(content): Fix font style on signup with passwordless flow
mozilla/fxa pull request #15949
Opened 2023-10-19 20:31 UTC by dschom

## Because

- This view didn't look like others

## This pull request

- Adds appropriate classes
- Removes some legacy hacks in _layout.scss

## Issue that this pull request solves

Closes: # (issue number)

## Checklist

_Put an `x` in the boxes that apply_

- [ ] My commit is GPG signed.
- [ ] If applicable, I have modified or added tests which pass locally.
- [ ] I have added necessary documentation (if appropriate).
- [ ] I have verified that my changes render correctly in RTL (if appropriate).

## Screenshots (Optional)

![image](https://github.com/mozilla/fxa/assets/94418270/6194f1a6-c3f4-4e3b-bcd3-cc5fb5a7a7c3)

## Other information (Optional)

Note this could probably use a follow up due to the comment here. It's largely outside the scope of account branding work, so the minimum fix will be applied here.

2023-10-19 22:34 UTC, bcolsson approved these changes

2023-10-23 16:33 UTC, vpomerleau requested changes
I'm not too familiar with the CSS setup for content-server, but I noticed that it is setup a bit differently here from the the `index` file. With the suggested change, the package builds successfully and LGTM to me locally.

2023-10-23 16:33 UTC, vpomerleau commented on packages/fxa-content-server/server/templates/pages/src/404.html
> +    <link rel="stylesheet" href="/styles/tailwind.out.css" />
Suggested change to address build error: this matches the stylesheet build for `index.html`. Making this change for all html files in this PR should resolve the error (tested locally and builds successfully).

```suggestion
    <!-- build:css(.tmp) /styles/main.css -->
    <link rel="stylesheet" href="/styles/main.css" />
    <!-- endbuild -->
    <!-- build:css(.tmp) /styles/tailwind.out.css -->
    <link rel="stylesheet" href="/styles/tailwind.out.css" />
    <!-- endbuild -->
```

2023-10-24 17:13 UTC, vpomerleau approved these changes

2023-10-24 17:17 UTC, merged