fix(payments): revert aria-disabled on submit
mozilla/fxa pull request #16007
Opened 2023-11-01 17:26 UTC by StaberindeZA

## Because

- aria-disabled=true doesn't disable the button, allowing the submit button to be pressed multiple times.

## This pull request

- Reverts the change from aria-disabled to disabled

## Issue that this pull request solves

Closes: #FXA-8590

## Checklist

_Put an `x` in the boxes that apply_

- [x] My commit is GPG signed.
- [x] If applicable, I have modified or added tests which pass locally.
- [x] I have added necessary documentation (if appropriate).
- [x] I have verified that my changes render correctly in RTL (if appropriate).

## Other information (Optional)

Ideally this change would not be necessary, and the PaymentForm would continue to use `aria-disabled`. However due to the difference in functionality provided by `disabled` and `aria-disabled`, additional work would be required to provide the desired user experience using `aria-disabled`.

For more information I found this page to be a good resource. [CSS Tricks - Making Disabled Buttons More Inclusive](https://css-tricks.com/making-disabled-buttons-more-inclusive/)

2023-11-02 19:57 UTC, sardesam requested changes
Thank you for giving this a try, Reino! Unfortunately, this is not an accessible solution and why it was removed in the first place. Adding that attribute is as good as having the button disappear on click. It can be very confusing to users with disabilities and ATs (each one operates differently depending on platform and settings).

An alternative approach is to add some additional css and js to disable focus and interactivity on the button without removing it from the web accessibility DOM entirely. That article you linked actually shows a very good and quick solution to make it work. It shouldn't take too long. We can also hop on a call and work on it together.

If this approach does not work, we might need to discuss with design/UX as the proposed solution is not inclusive and can alienate customers.

2023-11-02 20:44 UTC, StaberindeZA commented
> Thank you for giving this a try, Reino! Unfortunately, this is not an accessible solution and why it was removed in the first place. Adding that attribute is as good as having the button disappear on click. It can be very confusing to users with disabilities and ATs (each one which operate differently depending on platform and settings).
> 
> An alternative approach is to add some additional css and js to disable focus and interactivity on the button without removing it from the web accessibility DOM entirely. That article you linked actually shows a very good and quick solution to make it work. It shouldn't take too long. We can also hop on a call and work on it together.
> 
> If this approach does not work, we might need to discuss with design/UX as the proposed solution is not inclusive and can alienate customers.

Yeah agreed, this change isn't ideal and is definitely a temp "hotfix". Without this change, the button is still clickable and under certain conditions it creates a duplicate subscription.

That said, Is the approach you were thinking of in the article the one shown in Demo 3/3? We don't currently have a message for the submit button when it's disabled and it's being clicked. Is it fine not to have a message? If we do want a message, what should it be and where should it be?

2023-11-07 17:33 UTC, sardesam reviewed
Thank you for all the changes, Reino!

I tested with mouse, keyboard, and screen reader. It's amazing! Only one glitch keeps happening. How much effort would it be to fix? I haven't been able to create duplicate payments myself but right before the page refreshes, the button becomes enabled again.

Have you been able to re-create or know why that is happening/how to fix it? Would this cause a duplicate subscription?

2023-11-07 18:30 UTC, StaberindeZA commented
> Thank you for all the changes, Reino!
> 
> I tested with mouse, keyboard, and screen reader. It's amazing! Only one glitch keeps happening. How much effort would it be to fix? I haven't been able to create duplicate payments myself but right before the page refreshes, the button becomes enabled again.
> 
> Have you been able to re-create or know why that is happening/how to fix it? Would this cause a duplicate subscription?

Seems it was a pretty quick fix to keep the button disabled until the page "redirects". This PR just changes when `setInProgress(false)` is called. (This seems to be the cause of the button flashing enabled before "redirect")

Regarding STR for duplicate subscriptions, I've updated the commit message to include it in there, and repeated it here below.
* Existing customer with existing PayPal payment method
* Customer subscribes to a new product
* Customer clicks the subscribe button multiple times

2023-11-07 18:57 UTC, sardesam approved these changes
Thank you! r+

2023-11-07 20:33 UTC, merged