Reject Relay email masks on signup
mozilla/fxa pull request #16219
Opened 2024-01-03 16:29 UTC by vbudhram

## Because

- We don't want to create new accounts with Relay mask

## This pull request

- Disables the ability to create new accounts

## Issue that this pull request solves

Closes: # (issue number)

## Checklist

- [x] My commit is GPG signed.
- [x] If applicable, I have modified or added tests which pass locally.
- [ ] I have added necessary documentation (if appropriate).
- [ ] I have verified that my changes render correctly in RTL (if appropriate).

<img width="507" alt="Screenshot 2024-01-03 at 11 10 36 AM" src="https://github.com/mozilla/fxa/assets/1295288/927769f6-2b28-432e-80dd-0695585b18bc">

2024-01-03 17:02 UTC, chenba requested changes
The regex doesn't look right since no email address can end with just '@mozmail'.

2024-01-03 17:33 UTC, chenba commented on packages/fxa-content-server/app/scripts/views/index.js
> +    const relayMail = new RegExp('@mozmail.com$', 'i');
The `.` needs to be escaped in this case.  (Personally I prefer `string.endswith` for a simple match like this.)

2024-01-03 17:34 UTC, chenba approved these changes
👍  There's one small thing with the regex pattern but otherwise LGTM

2024-01-03 23:02 UTC, bcolsson requested changes

2024-01-03 23:02 UTC, bcolsson commented on packages/fxa-settings/src/components/Settings/PageSecondaryEmailAdd/en.ftl
> +add-secondary-email-mask = Email masks can’t be used as a secondary email
Can we leave a comment here that explains what "Email masks" are here? (Localizers for Mozilla Accounts may not be familiar with Firefox Relay.)

2024-01-09 17:17 UTC, bcolsson approved these changes

2024-01-09 17:19 UTC, vbudhram commented
@chenba Retagging you for review since I missed a requirement that it needs to support *.mozmail.com and relay.firefox.com email domains.

2024-01-09 17:45 UTC, chenba approved these changes
LGTM

2024-01-10 19:02 UTC, merged