feat(payments-paypal): Create PayPalManager getCustomerPayPalSubscriptions
mozilla/fxa pull request #16552
Opened 2024-03-12 14:53 UTC by xlisachan

## This pull request

- [x] creates PayPalManager getCustomerPayPalSubscriptions
  - [x] The method should take a stripe customer as a non-optional argument
  - [x] Return all customer subscriptions where collection method is send_invoice

## Issue that this pull request solves

Closes: FXA-8938

## Checklist

_Put an `x` in the boxes that apply_

- [x] My commit is GPG signed.
- [x] If applicable, I have modified or added tests which pass locally.

2024-03-13 12:38 UTC, StaberindeZA approved these changes
r+. lgtm

2024-03-13 13:48 UTC, StaberindeZA commented on libs/payments/paypal/src/lib/paypal.manager.ts
> +    return customer.subscriptions?.data.filter(
I left a similar comment on the other PR, but I just remembered that in the ADR 0040-stripe-typings, the team decided to never use expanded properties. I believe that applies to `customer.subscriptions` as well.

2024-03-13 16:37 UTC, StaberindeZA requested changes
After further investigation, looks like some changes might still be needed. Discussions on going.

2024-03-15 18:32 UTC, julianpoy commented on libs/payments/stripe/src/lib/stripe.manager.ts
> +  }
I think this belongs in the paypal manager - `send_invoice` is the collection method used for paypal subs.

2024-03-15 18:33 UTC, julianpoy commented on libs/payments/stripe/src/lib/stripe.manager.ts
> +      expand: ['subscriptions'],
Expand is not allowed in SP3 (see ADR Reino linked)

2024-03-15 18:33 UTC, julianpoy commented on libs/payments/stripe/src/lib/stripe.manager.ts
> +      throw new CustomerNoSubscriptionsError(customerId);
We can just return an empty array if the user has no subscriptions, no need to throw an error.

2024-03-15 18:35 UTC, julianpoy commented on libs/payments/stripe/src/lib/stripe.manager.spec.ts
> +  });
Factories should be used as close as possible to your tests, if possible. That way you're only creating the test data you absolutely need in a test, as well as guaranteeing no side-effects if one of your tests (or test subjects) happen to modify the data.

2024-03-18 15:02 UTC, StaberindeZA approved these changes
r+wc. Just 2 small comments, with nice to have changes, but non-blocking.

Thank you for the discussion on this ticket.

2024-03-18 15:45 UTC, merged