feat(payments): Add Upgrade - Purchase Details + Layout
mozilla/fxa pull request #18173
Opened 2024-12-30 19:25 UTC by xlisachan

## This pull request

- [x] Refactors `PurchaseDetails` component and removes `Details` component
- [x] Creates upgrade layout, i.e. app/[locale]/[offeringId]/upgrade/[interval]/[cartId]/layout.tsx and temporary `start` page
- [x] Updates SubscriptionTitle and adds it and UpgradePurchaseDetails to upgrade layout

## Issue that this pull request solves

Closes: FXA-7588

## Checklist

_Put an `x` in the boxes that apply_

- [x] My commit is GPG signed.
- [x] I have verified that my changes render correctly in RTL (if appropriate).

## Screenshots (Optional)
<img width="1109" alt="Screenshot 2025-02-18 at 11 01 32 AM" src="https://github.com/user-attachments/assets/f1b7a9aa-4211-4cf2-803c-a3bd631402a1" />

#### Previous Upgrade page
<img width="1032" alt="Screenshot 2025-02-11 at 5 13 54 PM" src="https://github.com/user-attachments/assets/3aa5adb8-aa3b-4786-9c19-146c1caaf58a" />

2025-01-14 22:36 UTC, xlisachan commented on libs/payments/customer/src/lib/util/stripeInvoiceToInvoicePreviewDTO.ts
> +  const taxAmounts = invoice[0].total_tax_amounts.map((amount) => ({
I reverted this update as we only need the total of the prorated invoice (I did not see the prorated amount being used anywhere other than in the legacy tests and stories).

2025-01-14 22:39 UTC, bcolsson approved these changes

2025-02-20 22:00 UTC, StaberindeZA reviewed
Still need to test, but wanted to leave some initial feedback comments in the mean time.

2025-02-20 22:00 UTC, StaberindeZA commented on libs/payments/cart/src/lib/cart.service.ts
> -        currency,
Isn't currency a required field for SP3? How are none default currency values determined, i.e. EUR etc?

2025-02-20 22:00 UTC, StaberindeZA commented on libs/payments/cart/src/lib/cart.service.ts
> +      fromPrice: 'fromPrice' in eligibility ? currentPrice : undefined,
nit. why the different names from vs current?

2025-02-21 15:18 UTC, StaberindeZA commented on libs/payments/ui/src/lib/server/components/SubscriptionTitle/index.tsx
> +const getComponentTitle = (cartState: CartState | CartEligibilityStatus) => {
`CartState` and `CartEligibilityStatus` should be separate input params

2025-02-24 17:49 UTC, StaberindeZA commented on libs/payments/cart/src/lib/cart.types.ts
> +};
Thank you for the quick chat. I'm happy to drop this commit, and follow this PR with the implementation we discussed.

2025-02-24 19:20 UTC, bcolsson requested changes

2025-02-24 19:20 UTC, bcolsson commented on libs/payments/ui/src/lib/server/components/UpgradePurchaseDetails/en.ftl
> +# $productName (String) - Name of the upgraded product (e.g. Mozilla VPN)
This comment either needs to be a group comment, or repeated for each string. Otherwise this comment will only appear for the first string below (`-daily`) but none of the others (`-weekly` etc.).

Also as I look at this again, the context about what (Daily) is referring to might not be clear- could you indicate in a comment what Daily / Weekly/ Monthly / Yearly is referring to?

2025-02-24 21:38 UTC, StaberindeZA approved these changes
r+. Thank you for the changes and leading the various discussions.

2025-02-25 18:18 UTC, bcolsson approved these changes

2025-02-25 18:38 UTC, merged