Feature/graceful shutdown support
mozilla/fxa pull request #5961
Opened 2020-07-16 11:00 UTC by enote-kane

## Because

I want to run the services in standard Docker/Kubernetes environment.

## This pull request

Adds support for handling `SIGTERM` (and `SIGINT` where missing) for the following services which currently do not react to such a signals:
* fxa-support-panel
* fxa-event-broker
* fxa-content-server

## Issue that this pull request solves

refs: #5921 (does *NOT* close)

## Checklist

_Put an `x` in the boxes that apply_

- [x] My commit is GPG signed.
- [ ] If applicable, I have modified or added tests which pass locally.
- [ ] I have added necessary documentation (if appropriate).

2020-08-18 20:50 UTC, clouserw commented
ping @jbuck @dannycoates @bbangert

2020-09-08 20:33 UTC, vbudhram commented
@enote-kane This has a merge conflict

2020-09-21 17:02 UTC, bbangert commented
@enote-kane this looks good, though we've moved some things around so some of this can be removed. fxa-event-broker and fxa-admin-server have both been moved to NestJS and now have proper shutdown. fxa-graphql-api and fxa-support-panel will also be moving to NestJS and get proper shutdown. So only the other ones in this PR are still needed.

Sorry about the delay in getting back to this, as we would like these services to shutdown gracefully.

2020-09-21 17:03 UTC, bbangert requested changes
See my other comment above.

2020-10-02 14:35 UTC, clouserw commented
Please reopen if you have the opportunity to rebase.  Thank you.

2020-10-02 14:35 UTC, closed without merging