feat(db): Create table to store user-customer relationship
mozilla/fxa pull request #6514
Opened 2020-09-21 21:48 UTC by jackiemunroe

## Because:

* We want to be able to tell if an FxA user has an associate Stripe Customer account without having to query Stripe

## This Commit:

* Creates the userCustomers table that will be used to associate FxA user ids with Stripe Customer ids

## Closes: #6158

## Checklist

_Put an `x` in the boxes that apply_

- [x ] My commit is GPG signed.

2020-09-21 21:58 UTC, jackiemunroe commented
@lmorchard when you have a sec, can you take a look at this and see if there is anything I overlooked? I was thinking about anything additional we might want to be stored here. I was on the fence about adding the createdAt, but decided to put it in there, since it _could_ be useful.

2020-09-21 22:41 UTC, lmorchard requested changes
Looks good, except for one tweak thanks to FxA weirdness - `uid` is a binary column throughout the DB, so we should do that here too

2020-09-21 22:41 UTC, lmorchard commented on packages/fxa-auth-db-mysql/lib/db/schema/patch-112-113.sql
> +  fxaUserId VARCHAR(255) PRIMARY KEY,
I think `createdAt` is a good idea. Though, `fxaUserId` should probably instead be `uid binary(16) NOT NULL PRIMARY KEY` for consistency & maybe joins with the `accounts` table. I don't remember why we use a `binary(16)` column here, though. Storage size maybe?

```
✗ mysql --host 127.0.0.1 -u root fxa -e 'show create table accounts'
...
CREATE TABLE `accounts` (
  `uid` binary(16) NOT NULL,
  `normalizedEmail` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `email` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
  `emailCode` binary(16) NOT NULL,
  `emailVerified` tinyint(1) NOT NULL DEFAULT '0',
  `kA` binary(32) NOT NULL,
  `wrapWrapKb` binary(32) NOT NULL,
  `authSalt` binary(32) NOT NULL,
  `verifyHash` binary(32) NOT NULL,
  `verifierVersion` tinyint(3) unsigned NOT NULL,
  `verifierSetAt` bigint(20) unsigned NOT NULL,
  `createdAt` bigint(20) unsigned NOT NULL,
  `locale` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `lockedAt` bigint(20) unsigned DEFAULT NULL,
  `profileChangedAt` bigint(20) unsigned DEFAULT NULL,
  `keysChangedAt` bigint(20) unsigned DEFAULT NULL,
  `ecosystemAnonId` text CHARACTER SET ascii COLLATE ascii_bin,
  PRIMARY KEY (`uid`),
  UNIQUE KEY `normalizedEmail` (`normalizedEmail`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci |`
```

2020-09-21 22:53 UTC, dannycoates commented on packages/fxa-auth-db-mysql/lib/db/schema/patch-112-113.sql
> +-- -- create userCustomers table for storing fxa user to stripe customer relationship
please add
```
SET NAMES utf8mb4 COLLATE utf8mb4_bin;

CALL assertPatchLevel('112');
```

to the top

2020-09-22 00:35 UTC, lmorchard commented on packages/fxa-auth-db-mysql/lib/db/schema/patch-112-113.sql
> +CREATE TABLE IF NOT EXISTS userCustomers (
Last nit I could think of here is maybe `userCustomers` should be `accountCustomers` for consistency, but wouldn't block on that

2020-09-22 00:35 UTC, lmorchard approved these changes

2020-09-22 17:54 UTC, dannycoates approved these changes
💯

2020-09-22 18:35 UTC, lmorchard approved these changes
:+1:

2020-09-22 18:37 UTC, merged