chore(config): Allow Firefox Desktop to request ecosystem telemetry scope
mozilla/fxa pull request #6601
Opened 2020-10-03 02:39 UTC by rfk

## Because

* Firefox Desktop will soon be able to calculate the ecosystem_user_id as part
  of its logn flow (https://bugzilla.mozilla.org/show_bug.cgi?id=1647588)
* Calculating this value the right way means deriving it like a scoped key,
  and the FxA server controls wht scoped-key metadata is available to whic
  clients.

## This pull request

* Allows the ecosystem_telemetry scope for the Firefox Desktop OAuth
  client in dev environments.
* Accompanies the production change requested in
  https://bugzilla.mozilla.org/show_bug.cgi?id=1668972

## Issue that this pull request solves

Closes: https://bugzilla.mozilla.org/show_bug.cgi?id=1668972 (for dev environments)

## Checklist

_Put an `x` in the boxes that apply_

- [x] My commit is GPG signed.
- ~~[ ] If applicable, I have modified or added tests which pass locally.~~
- ~~[ ] I have added necessary documentation (if appropriate).~~

2020-10-05 23:32 UTC, jbuck requested changes
I think you'll need to add this scope to https://github.com/mozilla/fxa/pull/6601/files#diff-071040d5f028a4dfefcb67b4f6d59144R398 as well right?

2020-10-06 00:05 UTC, rfk commented
Thanks, updated to add this to the list of scopes per https://bugzilla.mozilla.org/show_bug.cgi?id=1668972#c3

2020-10-06 00:06 UTC, rfk commented
(Your link seemed to go to existing code in my PR but I inferred the thing about the scopes table from the bugzilla comment, hoping that's what you meant...)

2020-10-06 01:53 UTC, jbuck approved these changes

2020-10-07 15:59 UTC, merged