feat(fxa-settings): add ConnectAnotherDevicePromo
mozilla/fxa pull request #6670
Opened 2020-10-12 18:40 UTC by meandavejustice

## This pull request

- adds the `<ConnectAnotherDevicePromo />` component

## Issue that this pull request solves

Closes: #5098

## Checklist

_Put an `x` in the boxes that apply_

- [x] My commit is GPG signed.
- [x] If applicable, I have modified or added tests which pass locally.
- [ ] I have added necessary documentation (if appropriate).

## Screenshots (Optional)

Please attach the screenshots of the changes made in case of change in user interface.

![mobile-promo-on-desktop](https://user-images.githubusercontent.com/1844554/95779852-d26f3d80-0c98-11eb-8d0f-b751123017ac.png)
![mobile-promo-on-mobile](https://user-images.githubusercontent.com/1844554/95779854-d26f3d80-0c98-11eb-8e32-0caadd0dcce0.png)

> 

## Other information (Optional)

Any other information that is important to this pull request.

2020-10-13 14:42 UTC, chenba commented on packages/fxa-settings/src/components/PageSettings/index.stories.tsx
> +  return true;
I vaguely remember seeing this logic somewhere else.  It would be nice to capture it in one place.

2020-10-13 14:43 UTC, chenba commented on packages/fxa-settings/src/components/PageSettings/index.stories.tsx
> +  return true;
haha I'm scrolling _up_... sorry I didn't mean somewhere else _in this PR_.  I meant before this PR.

2020-10-13 14:44 UTC, chenba commented on packages/fxa-settings/src/components/ConnectedServices/index.tsx
> +  }).length;
I don't think that `~` is necessary.

2020-10-13 14:45 UTC, chenba requested changes
Looks fine in ltr.  But doesn't look right in rtl though.

2020-10-13 20:18 UTC, meandavejustice commented
@chenba switched `!!~` to `!` and fixed rtl.

![rtl-handling](https://user-images.githubusercontent.com/1844554/95911655-c4d8b700-0d6f-11eb-8563-799703aa904d.png)

2020-10-13 20:35 UTC, jodyheavener commented
This is not aligned correctly ![Group](https://user-images.githubusercontent.com/6392049/95913270-f94d7280-0d71-11eb-9e9b-4ac65d96b65f.png)

2020-10-13 20:37 UTC, jodyheavener commented
> But doesn't look right in rtl though.

I'm all for getting rtl nailed down out of the gate, but it sounds like we will [also do a pass later](https://mozilla.slack.com/archives/CLV3KMZ8B/p1602252762309800?thread_ts=1602247625.308600&cid=CLV3KMZ8B) to make sure it's all good.

2020-10-13 20:37 UTC, chenba commented on packages/fxa-settings/src/components/PageSettings/index.stories.tsx
> +  return true;
> 
> 
> I don't know of any other place we filter like this, there is a place where we make [similar checks to show 
the icons](https://github.com/mozilla/fxa/pull/6677),

Hmm maybe it was in another package where I saw that logic.  So for this, looks like we need something that tells us if a device is a "mobile" device or not.  i.e.

```JavaScript
const isMobileDevice = (d) => d.deviceType === 'mobile' || d.name.toLowerCase().includes('ipad');
```

For the first filter we can just use `.filter(isMobileDevice)`.  For the second one, we do need to do `.filter(x => !isMobileDevice(x)`.

In addition having the "mobile device" logic in one place, I think it also reads better when we give that logic a name.

> but that would be weird to pull out into this story IMO

I don't understand what's weird about it.  I saw it in this PR so I suggested here.  If there's a more appropriate story, then let me know and I'll leave a note there.

2020-10-13 20:41 UTC, jodyheavener commented
I don't see a specific screen for it at mobile, but I'd probably center the "Missing or duplicate items?" text on mobile now that items above and below it are both centered 
<img width="474" alt="Screen Shot 2020-10-13 at 4 39 11 PM" src="https://user-images.githubusercontent.com/6392049/95913873-eb4c2180-0d72-11eb-826f-428875a7d6fa.png">

2020-10-14 15:52 UTC, meandavejustice commented
@chenba Added `isMobileDevice` util. much cleaner thanks for the suggestion.

@jodyheavener Fixed centering of missing items copy on mobile, and centered buttons, the playstore svg has a built in transparent padding so we just needed to match that for the app store icon.

2020-10-14 16:50 UTC, chenba commented on packages/fxa-settings/src/components/ConnectAnotherDevicePromo/app-store.svg
> +<svg version="1.1" id="US_UK_Download_on_the" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
LOL @ cliffhanger of an `id`

2020-10-14 17:03 UTC, chenba commented on packages/fxa-settings/src/components/ConnectedServices/index.test.tsx
> +  return true;
Could use `isMobileDevice` here.

2020-10-14 17:05 UTC, chenba commented
I was expecting `rtl` to look like 
![image](https://user-images.githubusercontent.com/198055/96021776-809ff200-0e15-11eb-8ef3-f216d22e4669.png)

Jody said that we can fix rtl stuff later though.

2020-10-14 17:06 UTC, chenba approved these changes
📱

2020-10-14 17:28 UTC, merged