fix(subscriptions): add Stripe customer to local DB on webhook
mozilla/fxa pull request #6694
Opened 2020-10-16 20:10 UTC by chenba

Because:
 - people can create customers and subscriptions directly via Stripe
   Dashboard

This commit:
 - insert a customer into the local DB when the Stripe customer is found
   with an email address

## Issue that this pull request solves

Closes: #6689 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My commit is GPG signed.
- [x] If applicable, I have modified or added tests which pass locally.

2020-10-17 06:00 UTC, bbangert requested changes
This isn't quite what I expected the solution to look like, and it looks like as-is it will start hitting Stripe anytime a cached record is asked for which would be a problem. I was expecting code in the webhook path to be updated, such that when the subscription created webhook fires and it gets to `updateCustomer`, it would do some checking to make sure a record was refreshed. If it wasn't, then it means we probably failed to link the db record, and that should be done and then the cache refreshed to force it in there.

2020-10-19 14:15 UTC, chenba commented on packages/fxa-auth-server/lib/payments/stripe.ts
> +    email?: string,
> Adding an argument in the middle of positional args like this makes me a bit nervous.

Agreed.  Unfortunately we do need the email to do a look up.

> I guess this function is only used in one place though?

Two.  VS Code knows about both though, so there's at least that.

2020-10-19 14:30 UTC, chenba commented on packages/fxa-auth-server/lib/payments/stripe.ts
> +    return this.fetchCustomer(uid, email, [
Before this patch, `fetchCustomer` uses Stripe's `customers.retrieve` with the Stripe customer id found in the DB record to do the lookup.  This patch uses Stripe's `customers.list` with the user's email address only when the the DB record is not found.  (The lookup with email was the method prior to the local DB changes.)  As far as this change goes, I don't understand how the reliance on Stripe has changed.  It merely switches the method of lookup based on the local DB.

2020-10-19 14:31 UTC, chenba commented on packages/fxa-auth-server/lib/routes/emails.js
> +async function updateStripeEmail(stripeHelper, uid, newPrimaryEmail) {
It is not.  I noticed that one of the params isn't used from VS Code's syntax highlighting.  Could undo if you find it noisy/distracting.

2020-10-19 14:49 UTC, chenba commented
> 
> 
> This isn't quite what I expected the solution to look like, and it looks like as-is it will start hitting Stripe anytime a cached record is asked for which would be a problem. I was expecting code in the webhook path to be updated, such that when the subscription created webhook fires and it gets to `updateCustomer`, it would do some checking to make sure a record was refreshed. 

`fetchCustomer` is in the code path of the new subscription webhook handler.  The call stack is something like this:

```
StripeHelper.fetchCustomer
StripeHelper.cachedCustomer
StripeHelper.customer
StripeHelper.refreshCachedCustomer
DirectStripeRoutes.updateCustomer
DirectStripeRoutes.updateCustomerAndSendStatus
DirectStripeRoutes.handleSubscriptionCreatedEvent
```

> If it wasn't, then it means we probably failed to link the db record, and that should be done and then the cache refreshed to force it in there.

When the Stripe customer is found in `fetchCustomer`, the returned value should be cached by `cachedCustomer`.

2020-10-19 14:53 UTC, chenba commented
@bbangert I must be missing or misunderstanding something.  The patch is adding (restoring) an alternative way of querying Stripe for a customer for when we do not have the Stripe customer but do have an email address.  Please let me know where my reasoning is breaking down in the patch.  Thanks!

2020-10-19 15:09 UTC, bbangert commented
@chenba Sre, we have the email address for all FxA customers when they hit our server. When the profile server hits us to see if the user has a subscription, we have the email address. This PR means that every auth request to FxA for every user will result in us hitting Stripe.

2020-10-19 15:36 UTC, chenba commented
> 
> 
> @chenba Sure, we have the email address for all FxA customers when they hit our server. When the profile server hits us to see if the user has a subscription, we have the email address. This PR means that every auth request to FxA for every user will result in us hitting Stripe.

@bbangert ah, ok, I thought the same issue would exist in the before local DB times, but there was an explicit `cacheOnly` that prevented the Stripe queries then.  The optional email param could act like that; I'll make some changes.  Thanks!

2020-10-19 16:28 UTC, bbangert commented
@chenba After a bit more thinking, I think there's a better way to prevent this situation without altering the complexity of existing code paths. We listen for a new Stripe event, `customer.created`, if we see it, then we verify we have the customer in the database, if we don't , then we add it. That's it, no other changes anywhere should be needed.

2020-10-19 16:53 UTC, chenba commented
> 
> 
> @chenba ... We listen for a new Stripe event, `customer.created`, if we see it, then we verify we have the customer in the database, if we don't , then we add it. ...

Ah the good ol' nip it in the bud approach.  I like it.

2020-10-19 16:54 UTC, chenba commented
Closing in favor of an approach where the customer would exist in the DB by the time a new subscription webhook event arrives.

2020-10-19 16:54 UTC, closed without merging