fix(gql-api): restore CatchGatewayError decorator
mozilla/fxa pull request #7197
Opened 2020-12-22 17:27 UTC by chenba

Because:
 - new settings was receiving JSON as error messages

This commit:
 - restore the decorator that was used to catch and re-throw errors
   prior to the NestJS conversion

## Issue that this pull request solves

Closes: #7128

2020-12-22 17:29 UTC, chenba commented
@bbangert I don't know why CatchGatewayError was removed.  Let me know if this is not the correct approach.

2021-01-04 15:35 UTC, vbudhram approved these changes
@chenba Should we add some basic tests for this? Otherwise LGTM 👍🏽 

<img width="578" alt="Screen Shot 2021-01-04 at 10 28 35 AM" src="https://user-images.githubusercontent.com/1295288/103551560-7e7b8b80-4e78-11eb-9cdb-c5b15e882fc7.png">

2021-01-04 15:35 UTC, vbudhram commented on packages/fxa-graphql-api/src/gql/lib/error.ts
> +      if (err.code && err.errno && err.message) {
Kind of stinks that auth-server and profile-server return different error objects and this is the only way to tell them apart.

Is there something in graphql that might make this better?

2021-01-04 17:18 UTC, bbangert commented
@chenba In NestJS, the correct way to do this would be to apply an Interceptor or ExceptionFilter on the class. There is a default interceptor which catches the errors and reports them (Sentry), but does not apparently handle reformatting the exceptions the same as the prior gateway exception catch did.

2021-01-04 17:18 UTC, bbangert requested changes
See other comment on using a NestJS filter.

2021-01-05 17:39 UTC, bbangert approved these changes
This can merge for now, we can do this with an exception filter in a follow-up.

2021-01-05 17:39 UTC, merged