localize settings header and footer
mozilla/fxa pull request #7335
Opened 2021-01-22 00:14 UTC by 6a68

## Because

- we want to localize the header and footer

## This pull request

- localizes the header and footer :-)

- Note: I feel a little weird about putting the strings for the footer (which lives in fxa-react) over in the fxa-settings App component's ftl file. This is in keeping with the approach from #7327 and I can't think of a better approach, but other suggestions welcome!

- Also note: I've used SpOnGeBoB cAsInG to convince myself that the l10n transforms are actually getting applied. But nobody else is doing that in the other l10n commits, so I can revert to normal casing if that's preferred. 
<img src="https://user-images.githubusercontent.com/96396/105428114-8884e480-5c03-11eb-9190-e7325c389ad3.png" width=100>

## Issue that this pull request solves

Closes: #5058

## Checklist

_Put an `x` in the boxes that apply_

- [x] My commit is GPG signed.
- [ ] If applicable, I have modified or added tests which pass locally.
- [ ] I have added necessary documentation (if appropriate).
- [ ] I have verified that my changes render correctly in RTL (if appropriate).

## Screenshots (Optional)

Please attach the screenshots of the changes made in case of change in user interface.

## Other information (Optional)

Any other information that is important to this pull request.

2021-01-22 17:57 UTC, LZoog commented
> Also note: I've used SpOnGeBoB cAsInG to convince myself that the l10n transforms are actually getting applied. But nobody else is doing that in the other l10n commits, so I can revert to normal casing if that's preferred.

FWIW I vaguely remember @meandavejustice doing this in Payments (I think?) a while back for the same reason, and @clouserw pushing back on the off chance something fails and an end-user sees the weird casing.

2021-01-22 18:11 UTC, 6a68 commented
Cool, thanks @LZoog! I think Dave and I both picked up that habit from m&m when we were working on lockbox

2021-01-25 17:23 UTC, meandavejustice requested changes
* One comment on translation copy.
* need to remove `packages/fxa-settings/package-lock.json`

2021-01-25 17:23 UTC, meandavejustice commented on packages/fxa-settings/public/locales/en-US/settings.ftl
> +header-title = Firefox accounts
This should be singular `Firefox account` according to figma

2021-01-25 18:29 UTC, 6a68 commented
Thanks for the review! Updated, re-pushed, ready for another look

2021-01-25 21:09 UTC, chenba approved these changes
WFM

2021-01-25 22:43 UTC, merged