feature(payments): Fix missing American Express logo
mozilla/fxa pull request #7913
Opened 2021-03-19 23:44 UTC by lesleyjanenorton

## Because

- We want the American Express logo to show up on the subscription confirmation and subscription information pages

## This pull request

- Adds a CSS rule to make the American Express logo visible

## Issue that this pull request solves

Closes: #7904 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My commit is GPG signed.
- [x] If applicable, I have modified or added tests which pass locally.
- [x] I have added necessary documentation (if appropriate).
- [x] I have verified that my changes render correctly in RTL (if appropriate).

## Screenshots (Optional)
.
<img width="648" alt="Screen Shot 2021-03-19 at 6 39 02 PM" src="https://user-images.githubusercontent.com/22355127/111851842-d3a93400-88e2-11eb-84d6-47a3f9d5ef4f.png">
<img width="697" alt="Screen Shot 2021-03-19 at 6 42 45 PM" src="https://user-images.githubusercontent.com/22355127/111851885-f8051080-88e2-11eb-9c69-65d759b92951.png">

## Other information (Optional)

Any other information that is important to this pull request.

2021-03-23 17:31 UTC, meandavejustice requested changes
This already exists at `.american` on line #61

2021-03-25 15:22 UTC, lesleyjanenorton commented
@meandavejustice Do you know of any instance where `.american` is being used? I'm not seeing it anywhere, but am hesitant to change it to `.amex` in case it's being added to the templates dynamically somewhere.

2021-03-25 16:50 UTC, meandavejustice commented
> @meandavejustice Do you know of any instance where .american is being used? I'm not seeing it anywhere, but am hesitant to change it to .amex in case it's being added to the templates dynamically somewhere.

I just grepped for it also and am not seeing it anywhere else, I believe at the time of writing this the `brand` was coming through as `american` or I thought it was going to be coming through as `american` instead of `amex`

I think it is safe to change :)

2021-03-25 19:43 UTC, lesleyjanenorton commented
Thanks, updated!

2021-03-25 19:54 UTC, meandavejustice approved these changes

2021-03-25 19:54 UTC, merged