fix(fxa-settings): changes the color of Delete Button
mozilla/fxa pull request #8228
Opened 2021-04-11 04:48 UTC by Deek9399

fixes #7417

## Because

- Delete button on the page 2 of 2 of Delete Account page has a primary(blue) color.

## This pull request

-changes the color of the delete button
-adds cta-caution to delete button, similar to delete account link.
-has a proper display on all screen widths

## Issue that this pull request solves

Closes: #7417 

## Checklist

_Put an `x` in the boxes that apply_

- [x] My commit is GPG signed.
- [ ] If applicable, I have modified or added tests which pass locally.
- [ ] I have added necessary documentation (if appropriate).
- [ ] I have verified that my changes render correctly in RTL (if appropriate).

## Screenshots (Optional)

Please attach the screenshots of the changes made in case of change in user interface.
![Screenshot from 2021-04-11 10-16-44](https://user-images.githubusercontent.com/69427216/114292837-1d82d580-9aaf-11eb-8306-8a6e75da1aa3.png)

## Other information (Optional)

Any other information that is important to this pull request.

2021-04-20 15:24 UTC, jodyheavener commented
Hi @Deek9399 I'm just checking in to see if this PR is ready for review or if you need a hand in getting it ready for review. Thanks!

2021-04-21 16:05 UTC, Deek9399 commented
@jodyheavener It has few checks failing, still I would like you to review it and  let me know how can I improve it.

2021-04-26 17:34 UTC, LZoog commented
@Deek9399 I took a gif recording of before and after...

Before:
![delete-account-btn-before](https://user-images.githubusercontent.com/13018240/116125517-34b6eb00-a68b-11eb-9eb3-f5bb547d14af.gif)

After:
![delete-account-btn](https://user-images.githubusercontent.com/13018240/116125357-02a58900-a68b-11eb-962c-341af15e3021.gif)

I think the only thing we need to do before this is ready would be to make sure the `disabled` state looks different than the enabled state, with your changes the button always appears disabled. It's not ideal that it "enables" before 8 characters, but I'm sure we have a separate issue for that, the issue in question only deals with updating the color so that's all your PR needs to cover. I'd also say, the dark red border looks a little funky in "disabled" state.

2021-04-27 16:04 UTC, jodyheavener requested changes
Marking this as ready for review but I'll +1 to @LZoog's suggestions

2021-04-28 13:16 UTC, Deek9399 commented
@jodyheavener, @LZoog  I will try to make the changes as suggested in previous comments and update it asap.

2021-05-07 16:11 UTC, jodyheavener commented
Hey @Deek9399 I just wanted to check in to see if you needed a hand with getting this PR across the finish line. Let me know if I can help!

2021-05-09 03:10 UTC, Deek9399 commented
@jodyheavener Sorry for the delay, I am working on it.

2021-05-10 07:32 UTC, Deek9399 commented
@jodyheavener I removed the dark red border that appeared in the disabled state, you can review this PR now. Let me know about any required changes.
Thank you :)

2021-05-10 15:59 UTC, jodyheavener requested changes
Super close - just a couple more thoughts!

2021-05-10 15:59 UTC, jodyheavener commented on packages/fxa-settings/src/components/PageDeleteAccount/index.tsx
> +                  className="cta-neutral mx-2 px-4  tablet:px-10"
Looks like an additional space made its way in here

2021-05-12 06:43 UTC, Deek9399 commented on packages/fxa-settings/src/components/PageDeleteAccount/index.tsx
> +                  tablet:px-10"
Yes!! @jodyheavener using `cta-caution mx-2 px-4 tablet:px-10` gives the required output with a lot less code. Let me know if something needs to be corrected.
 Thanks a lot, learning something new every day😃

2021-05-13 14:24 UTC, jodyheavener commented
@Deek9399 this looks great, thank you! Could you squash your two commits together (making sure the final one is signed)? I can merge it then :)

2021-05-13 16:41 UTC, Deek9399 commented
@jodyheavener I have made the required changes.

2021-05-13 20:36 UTC, jodyheavener approved these changes
@Deek9399 perfect! Thanks for this! 🥳

2021-05-13 20:37 UTC, merged