fix(fxa-settings): change clickable footer link spaces to fit width o…
mozilla/fxa pull request #8385
Opened 2021-04-23 09:23 UTC by Chiamaka-Uzuegbu

…f text for privacy notice and terms of services and forgot password links

## Because

-Clickable spaces are extended to the entire width of the footer.

## This pull request

-The clickable spaces now encompass the text of the link only.

## Issue that this pull request solves

Closes: # (7012)

## Checklist

_Put an `x` in the boxes that apply_

- [x] My commit is GPG signed.
- [ ] If applicable, I have modified or added tests which pass locally.
- [x] I have added necessary documentation (if appropriate).
- [ ] I have verified that my changes render correctly in RTL (if appropriate).

## Screenshots (Optional)

<img width="222" alt="footer problem" src="https://user-images.githubusercontent.com/73819616/115850469-ca4d4300-a41d-11eb-85a7-8676f313a6aa.PNG">
em.PNG…]()
<img width="224" alt="footer fix" src="https://user-images.githubusercontent.com/73819616/115850156-8f4b0f80-a41d-11eb-9f66-f6277a5b995d.PNG">

Please attach the screenshots of the changes made in case of change in user interface.

## Other information (Optional)

Any other information that is important to this pull request.

2021-04-23 09:30 UTC, Chiamaka-Uzuegbu commented
@jodyheavener , thanks for your review on my last PR. It got really messy trying to rebase and squash the commits into one, so I created a new branch and now have one commit to the fix I worked on with the necessary changes you directed me to make. Attached here is the link to the former PR, which you left a comment on: https://github.com/mozilla/fxa/pull/8301

2021-04-27 16:02 UTC, jodyheavener commented
Hi @Chiamaka-Uzuegbu! Thanks for the update. Mobile looks good but it looks like there is still some odd spacing at desktop size:

<img width="1791" alt="Capture d’écran, le 2021-04-27 à 11 59 00" src="https://user-images.githubusercontent.com/6392049/116274105-5a59f800-a750-11eb-9ccc-24554aa30822.png">

Are you seeing the same?

2021-04-27 16:05 UTC, jodyheavener requested changes
Going to mark this as changes requested, but feel free to ping me if you have questions

2021-04-28 19:57 UTC, Chiamaka-Uzuegbu commented
@jodyheavener thank you for your reviews. I have effected the change and hopefully this should look good on all screens now.

2021-04-29 18:37 UTC, jodyheavener requested changes
@Chiamaka-Uzuegbu It appears these are still full-width, are you seeing something different?

![Screen Shot 2021-04-29 at 2 35 21 PM](https://user-images.githubusercontent.com/6392049/116601227-43560a00-a8f8-11eb-95a1-4607c3c8027d.png)
![Screen Shot 2021-04-29 at 2 34 38 PM](https://user-images.githubusercontent.com/6392049/116601231-43eea080-a8f8-11eb-8fe4-0f9bf4e51b3c.png)

2021-05-07 16:14 UTC, jodyheavener commented
Hi @Chiamaka-Uzuegbu! Just checking in on this PR; if you have questions or need a hand getting it across the finish line let me know!

2021-05-07 17:27 UTC, Chiamaka-Uzuegbu commented
Hi @jodyheavener , I'll update the changes requested as soon as possible as I'm working on it.

2021-05-11 10:25 UTC, Chiamaka-Uzuegbu commented
Cool! Thanks a lot @jodyheavener. This should do it then. That means the last 2 links are wrapped in <div>s while the first one ( the one of logo) is left unmodified.

2021-05-11 10:38 UTC, Chiamaka-Uzuegbu commented
@jodyheavener . I've included your suggestions and committed the changes. Kindly review it.

2021-05-11 14:51 UTC, jodyheavener commented
Oops, @Chiamaka-Uzuegbu could you [GPG sign](https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification) your commit? Then I will merge :)

2021-05-11 20:44 UTC, merged