fix(fxa-payments-server): fix upgrade view layout
mozilla/fxa pull request #8812
Opened 2021-06-07 16:13 UTC by meandavejustice

## Because

- we need to allow users to view the upgrade page in a non broken way :)

## This pull request

- updated Product/SubscriptionCreate/index.scss to account for layout
differences with the `grid` rule. We needed different ratios based on
whether `.subscription-title` section was present or not.

## Issue that this pull request solves

Closes: #5369

## Checklist

_Put an `x` in the boxes that apply_

- [x] My commit is GPG signed.
- [x] If applicable, I have modified or added tests which pass locally.
- [x] I have added necessary documentation (if appropriate).
- [x] I have verified that my changes render correctly in RTL (if appropriate).

## Screenshots (Optional)

product page desktop
![image](https://user-images.githubusercontent.com/1844554/121053218-1fa0a200-c789-11eb-8409-ede6ad0ba99a.png)

product page mobile
![image](https://user-images.githubusercontent.com/1844554/121053382-4959c900-c789-11eb-9e31-5160bbc1e4c5.png)

upgrade page desktop
![image](https://user-images.githubusercontent.com/1844554/121053451-6098b680-c789-11eb-9265-ff581875adfd.png)

upgrade page mobile
![image](https://user-images.githubusercontent.com/1844554/121053508-727a5980-c789-11eb-9c02-94ffc7cff082.png)

2021-06-08 16:01 UTC, biancadanforth requested changes
Hey Dave; this is looking pretty good! I have a few thoughts:
* I am still seeing a horizontal scrollbar as Valentina reported in FXA-1919 (I also see this in `SubscriptionCreate` and `SubscriptionSuccess`). I don't see one in `SubscriptionUpgradeRoadblock`, so maybe there are some styles we could borrow from it?
* The `PlanUpgradeDetails` on the mobile view doesn't show the "Show details" link to expand it as in other mobile views (e.g. the `SubscriptionUpgradeRoadblock`).
* I know you didn't cause this, but what do you think about increasing the font slightly for "Current plan" and "New plan" (`.plan-upgrade-details-component p.plan-label` selector)? The text looks really small -- especially on desktop (11px). Maybe 14px? cc @jess-cook03

2021-06-08 16:18 UTC, meandavejustice commented
> I know you didn't cause this, but what do you think about increasing the font slightly for "Current plan" and "New plan" (.plan-upgrade-details-component p.plan-label selector)? The text looks really small -- especially on desktop (11px). Maybe 14px? cc @jess-cook03

@biancadanforth Can you file a follow up issue for this

2021-06-09 15:03 UTC, biancadanforth reviewed
>> I know you didn't cause this, but what do you think about increasing the font slightly for "Current plan" and "New plan" (.plan-upgrade-details-component p.plan-label selector)? The text looks really small -- especially on desktop (11px). Maybe 14px? cc @jess-cook03
>
> @biancadanforth Can you file a follow up issue for this

If this is what is in the Figma below; then that's fine. I didn't have a Figma to go off of. Unless Jess Cook says otherwise (now from the ping or after a design review of what's in stage), it's not worth filing a ticket for.

> > The PlanUpgradeDetails on the mobile view doesn't show the "Show details" link to expand it as in other mobile views (e.g. the SubscriptionUpgradeRoadblock).
> 
> This matches the designs from figma

What Figma are you referencing? Can you share a link? I haven't seen that one before.

>> I am still seeing a horizontal scrollbar as Valentina reported in FXA-1919 (I also see this in SubscriptionCreate and SubscriptionSuccess). I don't see one in SubscriptionUpgradeRoadblock, so maybe there are some styles we could borrow from it?
>
> I have not been able to reproduce the horizontal scrollbar. I'm seeing the same as the screenshots posted above at both android and iphone resolutions using responsive design view. Can you provide me with the steps you are using to reproduce?

Valentina's STR in [FXA-1919](https://jira.mozilla.com/browse/FXA-1919) indicate she is loading the page on a mobile device for one option. As for me, I was narrowing the browser window to trigger the media queries we have to change the layout. I can't tell from your mobile screenshots from DevTools whether there is a horizontal scrollbar or not, since the page is cropped at the bottom.

2021-06-10 14:05 UTC, meandavejustice commented
@biancadanforth I was using the Subscription Platform figma https://www.figma.com/file/KowVfoI16p90mURxLhh4D6/Subscription-Platform?node-id=2732%3A11094

> Valentina's STR in FXA-1919 indicate she is loading the page on a mobile device for one option. As for me, I was narrowing the browser window to trigger the media queries we have to change the layout. I can't tell from your mobile screenshots from DevTools whether there is a horizontal scrollbar or not, since the page is cropped at the bottom.

There are no horizontal scrollbars showing up when reproducing in the responsive design view. Which matches the dimensions Valentina was testing on.

2021-06-11 00:30 UTC, biancadanforth approved these changes
> @biancadanforth I was using the Subscription Platform figma https://www.figma.com/file/KowVfoI16p90mURxLhh4D6/Subscription-Platform?node-id=2732%3A11094

Thanks; that's the first time I've seen that Figma. There are a lot of things in there that don't match what we have in payments at the moment (like automatic redirects to the download page with the little green alert bar and discount codes).

Re: the "Show details link": in every other mobile view I've seen in our code (including the SubscriptionUpgradeRoadblock), we have the details cards with this link. So we can either be consistent with the rest of the UI as it is in payments now, or we can depart on this one screen to match this spec which deviates in numerous ways from our current state. My preference is to be consistent. It's not a blocker by any means.

> > Valentina's STR in FXA-1919 indicate she is loading the page on a mobile device for one option. As for me, I was narrowing the browser window to trigger the media queries we have to change the layout. I can't tell from your mobile screenshots from DevTools whether there is a horizontal scrollbar or not, since the page is cropped at the bottom.
> 
> There are no horizontal scrollbars showing up when reproducing in the responsive design view. Which matches the dimensions Valentina was testing on.

When I try it in a browser window at a width of 435px, I do see the scrollbar. When I try it in responsive design mode at a resolution of 360x692 pixels, I don’t see the horizontal scrollbar. Short of trying this on a mobile device, it would be hard to know with certainty that there is or isn't a horizontal scrollbar on mobile.

Given that you have only changed the `grid-row` property here, I doubt this change would fix what Valentina was seeing on her mobile device for the horizontal scrollbar, but we can certainly defer to QA to check. Unfortunately this can vary a lot, and since it's been a year, it's possible it will have resolved itself as well. I'll ask her in the ticket to verify that there is no horizontal scrollbar, since we are seeing mixed results here.

(For the record, I just spent 30 minutes trying various methods short of setting up a local HTTP proxy server to test this on my mobile phone, and while I got some pages rendering, I couldn't connect to the auth/MySQL server (e.g. to sign into my fake FxA account). If anyone has had success here, I welcome recommendations.)

2021-06-11 14:25 UTC, merged